const brand = 'Dentarova';

export const content = {
  en: {
    nav:['How it works','Services','Why us','FAQ','Contact'],
    heroEyebrow:'DENTAL GROWTH PARTNER FOR IRAQ',
    heroTitle:<>More patients.<br/><span>More appointments.</span><br/>Predictable growth.</>,
    heroText:'We build patient acquisition systems for dental clinics in Iraq — from Meta & Google Ads to landing pages, WhatsApp conversion and appointment follow-up.',
    primary:'Get free growth audit', secondary:'See how it works', trust:'Turkey-based team, specialized in the Iraq dental market',
    problemTitle:'Your clinic does not need more clicks. It needs a system that turns attention into appointments.',
    problemText:'Dentarova connects acquisition, conversion and follow-up into one measurable growth system — so you can see what brings leads, what creates appointments and what deserves more budget.',
    cards:[['01','ATTRACT','Reach people actively searching for dental treatments.'],['02','CAPTURE','Turn attention into qualified enquiries with focused landing pages.'],['03','CONVERT','Move leads into fast WhatsApp conversations and appointments.'],['04','SCALE','Measure performance and scale the channels that work.']],
    servicesTitle:'Everything your clinic needs to grow online.',
    services:['Meta & Google Ads','Conversion landing pages','Lead generation','WhatsApp conversion','Retargeting','Content strategy'],
    processTitle:'A growth system built around your clinic.',
    process:[['01','Audit','We find leaks in your current marketing, website and conversion flow.'],['02','Build','We create the campaigns, landing pages and follow-up journey.'],['03','Launch','We launch with tracking in place and optimize from real data.'],['04','Scale','We focus budget on the campaigns and audiences creating appointments.']],
    whyTitle:'Why Dentarova?',
    whyText:'You do not need another agency sending you reports full of clicks. You need a partner focused on the business outcome: qualified patients and booked appointments.',
    why:[['Iraq-focused','Every campaign, landing page and WhatsApp flow is built around how patients in Iraq search for and choose a clinic.'],['Full funnel','Ads, landing pages, WhatsApp and follow-up in one system, not disconnected pieces.'],['Clear numbers','Track leads, appointments and acquisition cost from day one.'],['Growth partner','Continuous testing and optimization instead of set-and-forget campaigns.']],
    resultsTitle:'Measure what actually matters.',
    resultsText:'Your marketing should connect spend to qualified enquiries and appointments — not vanity metrics.',
    metrics:[['LEADS','Qualified enquiries'],['BOOKINGS','Appointments generated'],['CPL','Cost per lead'],['ROI','Campaign return']],
    dashboardNote:'Sample dashboard — illustrative only',
    faqTitle:'Frequently asked questions',
    faq:[
      ['How fast can I expect results?','Most clinics start seeing qualified enquiries within the first 2–3 weeks of launching campaigns, once tracking and landing pages are live.'],
      ["What's the minimum ad budget?",'It depends on your city and competition. We give you a realistic budget recommendation during the free audit — there is no fixed minimum to get started.'],
      ['Do I need a long-term contract?','No long-term lock-in. We work month-to-month so you can evaluate results before committing further.'],
      ['Do you only work with clinics in Iraq?','Iraq is our core focus, which means every campaign, landing page and WhatsApp flow is built specifically around how patients in Iraq search for and choose a dental clinic.']
    ],
    ctaTitle:'Ready to find your clinic’s growth opportunities?',
    ctaText:'Get a free audit of your current online presence and a practical roadmap for attracting and converting more patients.',
    freeNote:'Free. No obligation. Practical recommendations.',
    formTitle:'Get your free growth audit',
    fields:['Clinic name','City / Country','Website or Instagram','WhatsApp number','Monthly ad budget'],
    submit:'Request my audit', sending:'Sending…',
    success:'Thanks — your growth audit request has been received.',
    error:'Something went wrong. Please try again.',
    whatsappIntro:'Hello Dentarova, I would like a free dental growth audit.',
    whatsappFloat:'Chat on WhatsApp',
    footer:'Dentarova — Dental Growth Partner for Iraq, based in Turkey.',
    contactEmail:'dentaro​va@gmail.com'.replace(/\u200b/g,''),
    phoneLabel:'WhatsApp'
  },
  tr: {
    nav:['Nasıl çalışır?','Hizmetler','Neden biz?','SSS','İletişim'],
    heroEyebrow:'IRAK\u2019TAKİ DİŞ KLİNİKLERİ İÇİN GROWTH PARTNER',
    heroTitle:<>Daha fazla hasta.<br/><span>Daha fazla randevu.</span><br/>Öngörülebilir büyüme.</>,
    heroText:'Irak\u2019taki diş klinikleri için Meta ve Google reklamlarından landing page, WhatsApp dönüşümü ve randevu takibine kadar uçtan uca hasta kazanma sistemleri kuruyoruz.',
    primary:'Ücretsiz growth analizi al', secondary:'Nasıl çalıştığını gör', trust:'Türkiye merkezli, Irak pazarına özel çalışan bir ekip',
    problemTitle:'Kliniğinizin daha fazla tıklamaya değil, tıklamaları randevuya çeviren bir sisteme ihtiyacı var.',
    problemText:'Dentarova; müşteri kazanımı, dönüşüm ve takip süreçlerini tek bir ölçülebilir growth sistemi altında birleştirir.',
    cards:[['01','ÇEK','Diş tedavisi arayan doğru kişilere ulaşın.'],['02','YAKALA','İlgiyi odaklı landing page’lerle nitelikli taleplere çevirin.'],['03','DÖNÜŞTÜR','Lead’leri hızlı WhatsApp görüşmelerine ve randevulara taşıyın.'],['04','ÖLÇEKLE','Sonuçları ölçün ve işe yarayan kanallara daha fazla yatırım yapın.']],
    servicesTitle:'Kliniğinizin online büyümesi için gereken her şey.',
    services:['Meta & Google Ads','Dönüşüm odaklı landing page','Lead generation','WhatsApp dönüşümü','Retargeting','İçerik stratejisi'],
    processTitle:'Kliniğiniz için tasarlanmış bir growth sistemi.',
    process:[['01','Analiz','Mevcut reklam, web sitesi ve dönüşüm akışınızdaki kayıpları buluyoruz.'],['02','Kur','Kampanyaları, landing page’leri ve takip sürecini oluşturuyoruz.'],['03','Yayınla','Takip sistemi hazır şekilde yayına alıyor ve gerçek verilerle optimize ediyoruz.'],['04','Ölçekle','Randevu üreten kampanya ve hedef kitlelere bütçeyi yönlendiriyoruz.']],
    whyTitle:'Neden Dentarova?',
    whyText:'Size sadece tıklama raporları gönderen başka bir ajansa ihtiyacınız yok. İhtiyacınız olan şey; nitelikli hasta ve randevu sonucuna odaklanan bir growth partner.',
    why:[['Irak\u2019a özel','Her kampanya, landing page ve WhatsApp akışı Irak\u2019taki hastaların arama ve karar verme alışkanlıklarına göre kuruluyor.'],['Uçtan uca','Reklam, landing page, WhatsApp ve takip tek sistemde, dağınık parçalar yerine.'],['Net veriler','Lead, randevu ve hasta kazanım maliyetini ilk günden takip edin.'],['Growth partner','Tek seferlik kampanya yerine sürekli test ve optimizasyon.']],
    resultsTitle:'Gerçekten önemli olanı ölçün.',
    resultsText:'Pazarlama bütçeniz gösteriş metriklerine değil, nitelikli taleplere ve randevulara bağlanmalı.',
    metrics:[['LEAD','Nitelikli talepler'],['RANDEVU','Oluşturulan randevular'],['CPL','Lead maliyeti'],['ROI','Kampanya getirisi']],
    dashboardNote:'Örnek panel — temsili gösterim',
    faqTitle:'Sıkça sorulan sorular',
    faq:[
      ['Ne kadar sürede sonuç görürüm?','Takip sistemi ve landing page yayına alındıktan sonra çoğu klinik ilk 2-3 hafta içinde nitelikli talepler almaya başlıyor.'],
      ['Minimum reklam bütçesi ne kadar?','Şehir ve rekabet durumuna göre değişir. Ücretsiz analiz sırasında size gerçekçi bir bütçe önerisi sunuyoruz; başlamak için sabit bir minimum yok.'],
      ['Uzun vadeli sözleşme gerekiyor mu?','Hayır, aylık çalışıyoruz. Sonuçları görmeden uzun vadeli taahhüt vermenizi istemiyoruz.'],
      ['Sadece Irak\u2019taki klinikler mi?','Evet, odağımız Irak — bu sayede her kampanya, landing page ve WhatsApp akışı Irak\u2019taki hastaların arama ve karar verme alışkanlıklarına özel olarak kuruluyor.']
    ],
    ctaTitle:'Kliniğinizin büyüme fırsatlarını keşfetmeye hazır mısınız?',
    ctaText:'Mevcut online varlığınız için ücretsiz analiz ve daha fazla hasta kazanmanız için uygulanabilir bir growth yol haritası alın.',
    freeNote:'Ücretsiz. Taahhüt yok. Uygulanabilir öneriler.',
    formTitle:'Ücretsiz growth analizi alın',
    fields:['Klinik adı','Şehir / Ülke','Website veya Instagram','WhatsApp numarası','Aylık reklam bütçesi'],
    submit:'Analizimi talep et', sending:'Gönderiliyor…',
    success:'Teşekkürler — growth analizi talebinizi aldık.',
    error:'Bir sorun oluştu. Lütfen tekrar deneyin.',
    whatsappIntro:'Merhaba Dentarova, ücretsiz dental growth analizi almak istiyorum.',
    whatsappFloat:"WhatsApp'tan yaz",
    footer:'Dentarova — Irak\u2019taki diş klinikleri için Türkiye merkezli Growth Partner.',
    contactEmail:'dentarova@gmail.com', phoneLabel:'WhatsApp'
  },
  ar: {
    nav:['كيف نعمل؟','الخدمات','لماذا نحن؟','الأسئلة الشائعة','تواصل معنا'],
    heroEyebrow:'شريك نمو لعيادات الأسنان في العراق',
    heroTitle:<>مزيد من المرضى.<br/><span>مزيد من المواعيد.</span><br/>نمو يمكن التنبؤ به.</>,
    heroText:'نبني أنظمة متكاملة لاكتساب المرضى لعيادات الأسنان في العراق، من إعلانات Meta وGoogle إلى صفحات الهبوط وتحويل واتساب ومتابعة المواعيد.',
    primary:'احصل على تحليل نمو مجاني', secondary:'اكتشف كيف نعمل', trust:'فريق مقره تركيا، متخصص في سوق العراق',
    problemTitle:'عيادتك لا تحتاج إلى نقرات أكثر، بل إلى نظام يحوّل الاهتمام إلى مواعيد.',
    problemText:'تربط Dentarova بين اكتساب العملاء والتحويل والمتابعة في نظام نمو واحد قابل للقياس.',
    cards:[['01','اجذب','الوصول إلى الأشخاص الذين يبحثون فعلياً عن علاجات الأسنان.'],['02','التقط','تحويل الاهتمام إلى استفسارات مؤهلة عبر صفحات هبوط مخصصة.'],['03','حوّل','نقل العملاء المحتملين إلى محادثات واتساب ومواعيد بسرعة.'],['04','وسّع','قياس الأداء وتوسيع القنوات التي تحقق نتائج.']],
    servicesTitle:'كل ما تحتاجه عيادتك للنمو عبر الإنترنت.',
    services:['إعلانات Meta وGoogle','صفحات هبوط للتحويل','توليد العملاء المحتملين','تحويلات واتساب','إعادة الاستهداف','استراتيجية المحتوى'],
    processTitle:'نظام نمو مصمم حول عيادتك.',
    process:[['01','تحليل','نحدد نقاط التسرب في التسويق والموقع ومسار التحويل الحالي.'],['02','بناء','ننشىء الحملات وصفحات الهبوط ومسار المتابعة.'],['03','إطلاق','نطلق النظام مع التتبع ونحسّن الأداء بناءً على البيانات.'],['04','توسّع','نركز الميزانية على الحملات والجمهور الذين يحققون المواعيد.']],
    whyTitle:'لماذا Dentarova؟',
    whyText:'لا تحتاج إلى وكالة أخرى ترسل تقارير مليئة بالنقرات. أنت بحاجة إلى شريك نمو يركز على النتيجة: مرضى مؤهلون ومواعيد محجوزة.',
    why:[['متخصصون في العراق','كل حملة وصفحة هبوط ومسار واتساب مصمم حسب طريقة بحث المرضى في العراق واختيارهم للعيادة.'],['نظام متكامل','الإعلانات وصفحات الهبوط وواتساب والمتابعة في نظام واحد، وليست أجزاء متفرقة.'],['أرقام واضحة','تتبع العملاء المحتملين والمواعيد وتكلفة الاكتساب منذ اليوم الأول.'],['شريك نمو','اختبار وتحسين مستمر بدلاً من الحملات الثابتة.']],
    resultsTitle:'قس ما يهم فعلاً.',
    resultsText:'يجب أن يربط التسويق الإنفاق بالاستفسارات المؤهلة والمواعيد، وليس بمؤشرات سطحية.',
    metrics:[['LEADS','استفسارات مؤهلة'],['BOOKINGS','مواعيد محجوزة'],['CPL','تكلفة العميل المحتمل'],['ROI','عائد الحملة']],
    dashboardNote:'عرض توضيحي فقط',
    faqTitle:'الأسئلة الشائعة',
    faq:[
      ['متى أبدأ برؤية النتائج؟','تبدأ معظم العيادات باستقبال استفسارات مؤهلة خلال أول 2-3 أسابيع بعد إطلاق الحملات وتفعيل نظام التتبع.'],
      ['ما هي الميزانية الإعلانية الأدنى؟','تختلف حسب المدينة والمنافسة، وسنقدم لك توصية واقعية للميزانية أثناء التحليل المجاني، دون حد أدنى ثابت للبدء.'],
      ['هل أحتاج إلى عقد طويل الأمد؟','لا، نعمل بنظام شهري بدون التزام طويل الأمد حتى تتمكن من تقييم النتائج أولاً.'],
      ['هل تعملون فقط مع عيادات في العراق؟','نعم، تركيزنا الأساسي هو العراق، ما يعني أن كل حملة وصفحة هبوط ومسار واتساب مصمم خصيصاً حسب طريقة بحث المرضى في العراق واختيارهم للعيادة.']
    ],
    ctaTitle:'هل أنت مستعد لاكتشاف فرص نمو عيادتك؟',
    ctaText:'احصل على تحليل مجاني لحضور عيادتك الرقمي وخارطة طريق عملية لجذب وتحويل المزيد من المرضى.',
    freeNote:'مجاني. بدون التزام. توصيات عملية.',
    formTitle:'احصل على تحليل نمو مجاني',
    fields:['اسم العيادة','المدينة / الدولة','الموقع أو Instagram','رقم WhatsApp','ميزانية الإعلانات الشهرية'],
    submit:'اطلب تحليلي', sending:'جارٍ الإرسال…',
    success:'شكراً — تم استلام طلب تحليل النمو الخاص بك.',
    error:'حدث خطأ. يرجى المحاولة مرة أخرى.',
    whatsappIntro:'مرحباً Dentarova، أريد الحصول على تحليل نمو مجاني لعيادتي.',
    whatsappFloat:'تواصل عبر واتساب',
    footer:'Dentarova — شريك نمو لعيادات الأسنان في العراق، مقرنا في تركيا.',
    contactEmail:'dentarova@gmail.com', phoneLabel:'واتساب'
  }
};
